

--QUERY1
--FIND THE NAMES OF SUPPLIERS,WHO HAVE SUPPLIED A TOTAL QUANTITY OF MORE THAN 10 PRODUCTS
-- AFTER JULY 2015. PUT THE RESULTS IN DESCENDING ORDER OF TOTAL QUANTITY

SELECT S_ID,SUP_NAME,SUM(QUANTITY) AS TTL_SUP_PROD
FROM F15_17_SUPP_INFO NATURAL JOIN F15_17_SUPPLIER 
WHERE SUP_DATE>'31-JUL-2015'
GROUP BY SUP_NAME,S_ID
HAVING SUM(QUANTITY)>10 
ORDER BY TTL_SUP_PROD DESC;

-----RESULTS FROM QUERY 1
-----S_ID SUP_NAME			    TTL_SUP_PROD
--------- ------------------------------                       ------------
----S006 JOE				      115
----S002 ADAM				      37
----S001 ROY				      27
----S004 KEITH				      22
----S003 GLORIA				      16




--QUERY2
--FIND THE CATEGORY WHOSE BRAND HAS MAXIMUM NUMBER OF PRODUCTS COMPARED TO 
--BRANDS OF OTHER CATEGORIES DISPLAY THE BRAND NAME,TOTAL PRODUCTS AND 
--CATEGORY ID.

SELECT PR.ID,PR.BRAND_NAME,TTL_PROD 
FROM(SELECT ID,BRAND_NAME,COUNT(*) AS TTL_PROD 
FROM F15_17_PRODUCT 
GROUP BY BRAND_NAME,ID 
HAVING COUNT(*) IN (SELECT MAX(COUNT(*)) 
FROM F15_17_PRODUCT 
GROUP BY BRAND_NAME,ID))P JOIN F15_17_PRODUCT PR ON P.ID=PR.ID AND P.BRAND_NAME=PR.BRAND_NAME 
GROUP BY PR.BRAND_NAME,TTL_PROD,PR.ID
ORDER BY ID;

 ------RESULT FROM QUERY2
--ID   BRAND_NAME 	     TTL_PROD
------ ----------      ----------
--C001 SAMSUNG		          2
--C001 SONY		              2
--C002 APPLE		          2
--C002 SAMSUNG		          2
--C003 APPLE		          2
--C004 ADIDAS		          2
--C006 US POLO		          2






--QUERY3
--FIND THE PRODUCT DETAILS WHICH ARE ORDERED MAXIMUM NUMBER OF TIMES BY 
--CUSTOMERS

SELECT PROD_NAME,P_ID,DESCRIPTION,BRAND_NAME,(SELECT COUNT(*) 
FROM F15_17_ORDERS_INFO O 
WHERE O.P_ID=F15_17_PRODUCT.P_ID)AS TTL  
FROM F15_17_PRODUCT 
WHERE P_ID IN(SELECT P_ID 
FROM F15_17_ORDERS_INFO 
GROUP BY P_ID 
HAVING COUNT(C_ID) IN(SELECT MAX(COUNT(C_ID)) 
FROM F15_17_ORDERS_INFO 
GROUP BY P_ID));


--RESULTS FROM QUERY 3

--PROD_NAME	     P_ID                            DESCRIPTION	                         BRAND_NAME         TTL						                              
----------------------                  ----                    ------------------------------------------------------------ ---------- ----------
--SHOES		     P017                WOMENS SPORTS SHOES SIZE 8	                        ADIDAS              3			      		
--IPHONE 6S PLUS     P008            A 9 PROCESSOR 12MP CAM HD RETINA DISPLAY           APPLE               3			      	 



 


--QUERY4
--FIND THE MONTH IN WHICH TOTAL QUANTITY OF PRODUCTS ORDERED IS MAXIMUM. 


SELECT TO_CHAR(ORDER_DATE,'MON') AS MONTH,SUM(QUANTITY) AS TTL_PRODUCTS
FROM F15_17_ORDERS_INFO
GROUP BY TO_CHAR(ORDER_DATE,'MON') 
HAVING SUM(QUANTITY) IN(SELECT MAX(SUM(QUANTITY)) 
FROM F15_17_ORDERS_INFO 
GROUP BY TO_CHAR(ORDER_DATE,'MON'));


---RESULTS FROM QUERY4
--MONTH	     TTL_PRODUCTS
-------------- ------------
--OCT	                    16


--QUERY5
--FIND THE BRAND NAME FROM WHICH QUANTITY OF PRODUCTS ORDERED BY A CUSTOMER IS GREATER 
--THAN OR EQUAL TO 5 BEFORE NOVEMBER 2015.DISPLAY BRAND NAME AND TOTAL QUANTITY OF PRODUCTS ORDERED IN 
--ASCENDING ORDER OF TOTAL QUANTITY 

SELECT BRAND_NAME,SUM(QUANTITY) AS TTL_ORDERED_PROD
FROM F15_17_PRODUCT P, F15_17_ORDERS_INFO O 
WHERE P.P_ID=O.P_ID 
AND ORDER_DATE< '01-NOV-2015'
GROUP BY BRAND_NAME 
HAVING SUM(QUANTITY) >=5
ORDER BY TTL_ORDERED_PROD;

---RESULTS FROM QUERY5

--BRAND_NAME TTL_ORDERED_PROD
------------ ----------------
--APPLE			  5
--TASSO			  5
--US POLO 		  20


--QUERY6
--FIND THE DETAILS OF THE PRODUCT, SUPPLIERS OF THE PRODUCT WHICH IS RETURNED BACK MAXIMUM 
--NUMBER OF TIMES

SELECT DISTINCT P.BRAND_NAME,P.PROD_NAME,P.DESCRIPTION,S.SUP_NAME,S.SUP_CONTACT
FROM F15_17_PRODUCT P 
JOIN F15_17_SUPPLIES U ON P.P_ID=U.P_ID 
JOIN F15_17_SUPPLIER S ON S.S_ID=U.S_ID 
JOIN F15_17_RETURNS_INFO R ON U.P_ID=R.P_ID
WHERE R.P_ID IN(SELECT P_ID 
FROM F15_17_RETURNS_INFO
GROUP BY P_ID 
HAVING COUNT(*) IN(SELECT MAX(COUNT(*)) 
FROM F15_17_RETURNS_INFO 
GROUP BY P_ID)); 

--RESULTS FROM QUERY 6

--BRAND_NAME       PROD_NAME  DESCRIPTION		SUP_NAME	          SUP_CONTACT		                                                                             			                                                                                                        
-------------- -------------------- ------------------------------------------------------------ ------------------------------ --------------------
--ADIDAS	   SHOES	   WOMENS SPORTS SHOES SIZE 8	ANNIE            7408922020			                                                                                   			                                                                                                             		                                                                                             			                                                                                            
--QUERY7
--FIND THE DETAILS OF SUPPLIERS WHO SUPPLIES ALL PARTS FROM CATEGORY 'C006'

SELECT S_ID,SUP_NAME,SUP_CONTACT,SUP_EMAILID 
FROM F15_17_SUPPLIER S 
WHERE NOT EXISTS
(SELECT P_ID FROM F15_17_PRODUCT P WHERE ID='C006' 
MINUS 
(SELECT P_ID FROM F15_17_SUPPLIES U WHERE U.S_ID=S.S_ID));

--RESULTS FROM QUERY 7

--S_ID SUP_NAME			    SUP_CONTACT 	 SUP_EMAILID
------ ------------------------------ -------------------- ------------------------------
---S006 JOE			    7169078690		 JOE@YAHOO.COM
 

--QUERY8
--FIND THE DETAILS OF THE PRODUCTS WHICH ARE NOT ORDERED EVEN ONCE

SELECT P_ID,PROD_NAME,BRAND_NAME,DESCRIPTION 
FROM F15_17_PRODUCT 
WHERE P_ID NOT IN
(SELECT P_ID FROM F15_17_ORDERS);

--RESULTS FROM QUERY 8
--P_ID PROD_NAME		  BRAND_NAME              DESCRIPTION
------ -------------------- ---------- ------------------------------------------------------------
--P021 JACKET		                PUMA	                       LEATHER JACKET SIZE 44
--P019 PRESSURE COOKER	   PRESTIGE                 3 LITERS ALUMINIUM COOKER
--P009 GALAXY S6		   SAMSUNG              EXYNOS PROCESSOR 16MP CAM 5.7 INCH HD DISPLAY
--P012 MACBOOK PRO	              APPLE                        I7 PROCESSOR 1TB HDISK 15 INCH RETINA DISPLAY


--QUERY9
--FIND THE CATEGORY DETAILS AND THE TOTAL NUMBER OF PRODUCTS IN EACH CATEGORY. DISPLAY THE 
--CATEGORY NAME,CATEGORY ID AND TOTAL NUMBER OF PRODUCTS IN DESCENDING ORDER.

SELECT ID,CATEGORY_NAME,
(SELECT COUNT(*) 
FROM F15_17_PRODUCT 
WHERE F15_17_CATEGORY.ID=F15_17_PRODUCT.ID) AS TOTAL_PRODUCTS 
FROM F15_17_CATEGORY 
ORDER BY TOTAL_PRODUCTS DESC;

--RESULTS FROM QUERY9
--ID   CATEGORY_NAME		    TOTAL_PRODUCTS
------ ------------------------------ --------------
--C001 ELECTRONICS				 6
--C002 MOBILES					 5
--C006 CLOTHING				     5
--C003 LAPTOPS					 4
--C004 SPORTS ACCESSORIES 	     3
--C005 HOME AND KITCHEN		     2


--QUERY10
--FIND ALL THE PRODUCTS IN CATEGORY 'C003' OR CATEGORY 'C004' WHICH  WERE LATEST SHIPPED 

SELECT PR.PROD_NAME,LATEST_DT,PR.DESCRIPTION 
FROM(SELECT DISTINCT(P.P_ID),MAX(S.SHIP_DATE) AS LATEST_DT
FROM F15_17_PRODUCT P,F15_17_SHIPS_INFO S 
WHERE (ID='C003' OR ID='C004') AND P.P_ID=S.P_ID 
GROUP BY P.P_ID) RESULT JOIN F15_17_PRODUCT PR ON RESULT.P_ID=PR.P_ID;

--RESULTS FROM QUERY10

--PROD_NAME	           LATEST_DT                                      DESCRIPTION
----------------------                        ---------                                ------------------------------------------------------------
--ALIENWARE LAPTOP      19-SEP-15                   I7 PROCESSOR 1TB HDISK 14 INCH DISPLAY
--SHOES		            15-NOV-15                      WOMENS SPORTS SHOES SIZE 8
--SOCCER BALL	           18-AUG-15                      MACHINE STITCHED USA COUNTRY BALL
--ATIV BOOK 9 SPIN       10-NOV-15                    I7 PROCESSOR 250GB HDISK 13.3 INCH TOUCH DISPLAY
--SHOES		         10-OCT-15                      MENS ATHLETIC SHOES SIZE 10
--MACBOOK AIR	        01-OCT-15 I5                  PROCESSOR 250GB HDISK 13 INCH DISPLAY


--QUERY11
--FIND ALL THE PRODUCTS WHICH WERE DELIVERED TO CUSTOMER ON THE SAME DAY AS ORDERED
--DISPLAY PRODUCT ID,NAME AND ITS BRAND

SELECT P_ID,PROD_NAME,BRAND_NAME
FROM F15_17_PRODUCT 
WHERE P_ID IN(SELECT P_ID 
FROM F15_17_ORDERS_INFO O 
WHERE P_ID IN(SELECT P_ID 
FROM F15_17_SHIPS S 
WHERE O.ORDER_DATE=S.DLVRY_DT));

--RESULTS FROM QUERY11
--P_ID PROD_NAME		  BRAND_NAME
------ -------------------- ----------
--P014 ATIV BOOK 9 SPIN	       SAMSUNG
--P017 SHOES		           ADIDAS
--P023 T-SHIRT		           US POLO




--QUERY12
--FIND THE DETAILS OF THE CUSTOMER WHO HAS PLACED THE ORDER  MAXIMUM NUMBER OF 
--TIMES

SELECT CUST_NAME,CUST_CONTACT,CUST_EMAILID,(SELECT COUNT(*) 
FROM F15_17_ORDERS_INFO 
WHERE F15_17_CUSTOMER.C_ID=F15_17_ORDERS_INFO.C_ID) AS TTL
FROM F15_17_CUSTOMER 
WHERE C_ID IN(SELECT C_ID 
FROM F15_17_ORDERS_INFO 
GROUP BY  C_ID 
HAVING COUNT(*) IN(SELECT MAX(COUNT(*)) 
FROM F15_17_ORDERS_INFO GROUP BY C_ID));

--RESULTS FROM QUEERY 12
--CUST_NAME    CUST_CONTACT	  CUST_EMAILID		              TTL 		
---------------------- -------------------- ------------------------------ ----------
--JUDE		     7438568798		  JUDE@HOTMAIL.COM		4	  



--QUERY13
--FIND THE DETAILS OF THE MALE EMPLOYEE WHO HAS SHIPPED MORE NUMBER OF PRODUCTS THAN ALL OF THE FEMALE EMPLOYEES

SELECT SSN,EMP_NAME,EMP_SAL,EMP_CONTACT,COUNT(*)AS TTL_SHPD 
FROM F15_17_EMPLOYEE NATURAL JOIN F15_17_SHIPS_INFO 
WHERE GENDER='M' 
GROUP BY SSN,EMP_NAME,EMP_SAL,EMP_CONTACT 
HAVING COUNT(*) >ALL(SELECT COUNT(*) 
FROM F15_17_SHIPS_INFO NATURAL JOIN F15_17_EMPLOYEE 
WHERE GENDER='F' GROUP BY SSN);

--RESULTS FROM QUERY13

--SSN	  EMP_NAME			    EMP_SAL         EMP_CONTACT 	       TTL_SHPD
----------- ------------------------------ ---------- -------------------- ----------
--123451001 DUKE				5000              6823131880	                    4
--123451005 GLENN 			  3000                9346251324	                   4
--123451002 SEAN				3500             7406922020	                       5		  	      
	 

--QUERY14
--FIND THE DETAILS OF THE YOUNGEST FEMALE CUSTOMER AND TOTAL NUMBER OF PRODUCTS SHE HAS ORDERED


SELECT DISTINCT CUST_NAME,CUST_CONTACT,CUST_EMAILID,(SELECT COUNT(*) 
FROM F15_17_ORDERS_INFO O 
WHERE F15_17_CUSTOMER.C_ID=O.C_ID)AS TTL_PROD_ORDERED 
FROM F15_17_CUSTOMER 
WHERE C_ID IN(SELECT C_ID 
FROM F15_17_ORDERS_INFO NATURAL JOIN F15_17_CUSTOMER 
WHERE DOB IN(SELECT MAX(DOB) 
FROM F15_17_CUSTOMER  
WHERE GENDER='F'));

---RESULTS FROM QUERY 14
-- 
--CUST_NAME	     CUST_CONTACT	  CUST_EMAILID			               TTL_PROD_ORDERED
---------------------- -------------------- ------------------------------ ----------------
--BELLA		     7856854321 	        BELLA@OUTLOOK.COM                          2		         		
--QUERY15
---FIND THE CUSTOMER WHO HAS SPENT MAXIMUM MONEY ON ORDERS. DISPLAY CUSTOMER 
--ID,NAME AND TOTAL AMOUNT SPENT

SELECT DISTINCT F15_17_ORDERS_INFO.C_ID,F15_17_CUSTOMER.CUST_NAME,MAXAMT 
FROM(SELECT C_ID,SUM(UNIT_SP*QUANTITY) AS MAXAMT 
FROM  F15_17_ORDERS_INFO 
GROUP BY C_ID 
HAVING SUM(UNIT_SP*QUANTITY) IN (SELECT MAX(SUM(UNIT_SP*QUANTITY)) 
FROM F15_17_ORDERS_INFO GROUP BY C_ID))R 
JOIN F15_17_ORDERS_INFO ON R.C_ID=F15_17_ORDERS_INFO.C_ID 
JOIN F15_17_CUSTOMER ON R.C_ID=F15_17_CUSTOMER.C_ID; 

--RESULTS FROM QUERY 15

--C_ID           CUST_NAME		      MAXAMT
----                -------------------- ----------
CU17                   CHRIS			5200

SELECT CUST_NAME,C.C_ID,COUNT(*) as ttl_orders FROM
F15_17_CUSTOMER C, F15_17_ORDERS O 
WHERE C.C_ID=O.C_ID 
GROUP BY CUST_NAME,C.C_ID ORDER BY COUNT(*) DESC;



