CREATE TABLE F15_17_EMPLOYEE(SSN char(9),
EMP_NAME VARCHAR(30) NOT NULL,
EMP_SAL NUMBER(8),
EMP_CONTACT VARCHAR2(20),
GENDER VARCHAR2(6) CHECK(GENDER='M' OR GENDER='F'),
EMP_EMAILID VARCHAR2(30) UNIQUE,
PRIMARY KEY (SSN));

CREATE TABLE F15_17_CATEGORY(ID CHAR(4), CATEGORY_NAME VARCHAR2(30) CHECK(CATEGORY_NAME='ELECTRONICS' OR CATEGORY_NAME='MOBILES' OR CATEGORY_NAME='LAPTOPS' OR CATEGORY_NAME='SPORTS ACCESSORIES' OR CATEGORY_NAME='HOME AND KITCHEN' OR CATEGORY_NAME='CLOTHING') NOT NULL,
PRIMARY KEY(ID));

CREATE TABLE F15_17_PRODUCT(P_ID CHAR(4),
BRAND_NAME VARCHAR2(10),
PROD_NAME VARCHAR2(20),
DESCRIPTION VARCHAR2(60),
ID CHAR(4),
PRIMARY KEY(P_ID),
FOREIGN KEY(ID) REFERENCES F15_17_CATEGORY(ID));

CREATE TABLE F15_17_SUPPLIER(S_ID CHAR(4),
SUP_NAME VARCHAR2(30) NOT NULL,
SUP_CONTACT VARCHAR2(20) ,
GENDER VARCHAR2(6) CHECK(GENDER='M' OR GENDER='F'),
SUP_EMAILID VARCHAR2(30) UNIQUE,
PRIMARY KEY(S_ID));

CREATE TABLE F15_17_CUSTOMER(C_ID CHAR(4),
CUST_NAME VARCHAR2(20) NOT NULL,
GENDER VARCHAR(6) CHECK(GENDER='M' OR GENDER='F'),
DOB DATE,
CUST_EMAILID VARCHAR2(30) UNIQUE,
CUST_CONTACT VARCHAR2(20),
CUST_ADDRESS VARCHAR2(60),
PRIMARY KEY(C_ID));

CREATE TABLE F15_17_SUPPLIES(S_ID CHAR(4),
P_ID CHAR(4),
PRIMARY KEY(S_ID,P_ID),
FOREIGN KEY(S_ID) REFERENCES F15_17_SUPPLIER(S_ID),
FOREIGN KEY(P_ID) REFERENCES F15_17_PRODUCT(P_ID));

CREATE TABLE F15_17_SUPP_INFO(S_ID CHAR(4),
P_ID CHAR(4),
UNIT_CP NUMBER(8),
QUANTITY NUMBER(8),
SUP_DATE DATE,
PRIMARY KEY(S_ID,P_ID,UNIT_CP,QUANTITY,SUP_DATE),
FOREIGN KEY(S_ID,P_ID) REFERENCES F15_17_SUPPLIES(S_ID,P_ID));

CREATE TABLE F15_17_ORDERS(C_ID CHAR(4),
P_ID CHAR(4),
PRIMARY KEY(C_ID,P_ID),
FOREIGN KEY(C_ID) REFERENCES F15_17_CUSTOMER(C_ID),
FOREIGN KEY(P_ID) REFERENCES F15_17_PRODUCT(P_ID));

CREATE TABLE F15_17_ORDERS_INFO(C_ID CHAR(4),
P_ID CHAR(4),
ORDER_DATE DATE,
UNIT_SP NUMBER(8),
QUANTITY NUMBER(8),
PRIMARY KEY(C_ID,P_ID,ORDER_DATE,UNIT_SP,QUANTITY),
FOREIGN KEY(C_ID,P_ID) REFERENCES F15_17_ORDERS(C_ID,P_ID));

CREATE TABLE F15_17_RETURNS(C_ID CHAR(4),
P_ID CHAR(4),
ISSUE VARCHAR2(40) NOT NULL,
PRIMARY KEY(C_ID,P_ID),
FOREIGN KEY(C_ID) REFERENCES F15_17_CUSTOMER(C_ID),
FOREIGN KEY(P_ID) REFERENCES F15_17_PRODUCT(P_ID));

CREATE TABLE F15_17_RETURNS_INFO(C_ID CHAR(4),
P_ID CHAR(4),
RET_DATE DATE,
QUANTITY NUMBER(8),
PRIMARY KEY(C_ID,P_ID,RET_DATE,QUANTITY),
FOREIGN KEY(C_ID,P_ID) REFERENCES F15_17_RETURNS(C_ID,P_ID));

CREATE TABLE F15_17_SHIPS(SSN CHAR(9),
C_ID CHAR(4),
P_ID CHAR(4),
DLVRY_DT DATE,
PRIMARY KEY(SSN,C_ID,P_ID),
FOREIGN KEY(SSN) REFERENCES F15_17_EMPLOYEE(SSN),
FOREIGN KEY(C_ID) REFERENCES F15_17_CUSTOMER(C_ID),
FOREIGN KEY(P_ID) REFERENCES F15_17_PRODUCT(P_ID));

CREATE TABLE F15_17_SHIPS_INFO(SSN CHAR(9),
C_ID CHAR(4),
P_ID CHAR(4),
QUANTITY NUMBER(8),
SHIP_DATE DATE,
PRIMARY KEY(SSN,C_ID,P_ID,QUANTITY,SHIP_DATE),
FOREIGN KEY(SSN,C_ID,P_ID) REFERENCES F15_17_SHIPS(SSN,C_ID,P_ID));